### ISSUE TITLE
Improve watch

### ISSUE THREAD

**Issue by unional** [typed-typings/npm-batch#1]
@blakeembrey any way to improve on this?
https://github.com/typed-typings/npm-batch/blob/master/package.json#L3
- `index.d.ts` can reference other files (e.g. in `lib/` for other repo)
- `typings.json` does not capture that (files in `main`/`browser`/`files` can reference other files)
- root `tsconfig.json` can use `exclude` instead of `files`.

One way I can think of is `./**/*.d.ts`, but that means it would also pick up `.d.ts` in `typings` or `source`.
Can I do `['./**/*.d.ts', '!./typings', '!./out']`?

**Comment by unional** [comment]
Also, what's your opinion on running `watch` as a process?
`"watch": "ts-node scripts/watch.ts index.d.ts &"`
(in generator, I'm now doing `ts-node` instead as I get typings of `is-callable` and `onchange` into registry. :smirk:)

**Comment by blakeembrey** [comment]
I would be using the `onchange` CLI. `onchange **/*.d.ts -e bundle/** -- npm test` or something like that. It'd be good to have PRs for the changes you made, I wasn't aware of a lot of the things you changed until now.

**Comment by unional** [comment]
The onchange CLI won't work? Because that means the author need to install `npm i -g onchange` (in the context of `generator-typings`).

> It'd be good to have PRs for the changes you made

I was using this repo as a test, so didn't create branch and PR. But yes. I can and I will. :smile:

**Comment by blakeembrey** [comment]
No, it always works. That's the whole way `typings` works locally. When you use NPM scripts, the PATH is set locally. That's the only reason the code also currently works.

**Comment by unional** [comment]
I tried:

``` sh
/path/npm-batch > onchange
# ~bash: onchange: command not found
```

What did I miss?

**Comment by blakeembrey** [comment]
It needs to be an NPM script.

**Comment by unional** [comment]
OH!!!! Thanks. :+1:

**Comment by unional** [comment]
> Also, what's your opinion on running watch as a process?
> "watch": "ts-node scripts/watch.ts index.d.ts &"

What about this?

**Comment by blakeembrey** [comment]
Why would you background it? NPM and backgrounding doesn't really work well, so I'd avoid it. Isn't the right way to keep it open and continue running? `onchange index.d.ts -- npm run test`?

**Comment by unional** [comment]
Background it so I can keep working and run test on the same console.
Currently it's `onchange ... -- npm run build`, only build the bundle (so that it will be reflected immediately on IDE for writing tests).

There will be a `"tdd": "onchange ... -- npm run build && npm run test"`.

EDIT: Understand that background might not make much sense as use need to kill them manually. :stuck_out_tongue:

**Comment by blakeembrey** [comment]
Yeah, don't background. It's confusing. I'd just have `"test": "npm run bundle && ts-node test.ts"` and use that for the onchange script like `"test-watch": "onchange '*.d.ts' -- npm run test"` - the glob will need to be fixed though.
